Repository wtsi-npg/npg_irods, pull requests merged in 2018-03, with the labels that each got.

#164 Fix for handling initargs and update for relative paths in tar output
  bin/npg_gridion_run_monitor.pl
  lib/WTSI/NPG/HTS/ONT/GridIONRunMonitor.pm
  lib/WTSI/NPG/HTS/ONT/GridIONRunPublisher.pm
  t/lib/WTSI/NPG/HTS/ONT/GridIONRunAuditorTest.pm
  t/lib/WTSI/NPG/HTS/ONT/GridIONRunPublisherTest.pm
Labels: bug, bump minor, enhancement, for next release

#177 Replaced RENCI FTP site
  .travis.yml
Labels: enhancement, for next release

#181 Support loading PacBio RSII files created using out of date reagents
  MANIFEST
  lib/WTSI/NPG/HTS/PacBio/RunPublisher.pm
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.1.bax.h5
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.1.log
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.1.subreads.fasta
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.1.subreads.fastq
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.2.bax.h5
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.2.log
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.2.subreads.fasta
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.2.subreads.fastq
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.3.bax.h5
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.3.log
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.3.subreads.fasta
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.3.subreads.fastq
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.bas.h5
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.sts.csv
  t/data/pacbio/superfoo/60180_1430/A01_1/Analysis_Results/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.sts.xml
  t/data/pacbio/superfoo/60180_1430/A01_1/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.1.xfer.xml
  t/data/pacbio/superfoo/60180_1430/A01_1/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.2.xfer.xml
  t/data/pacbio/superfoo/60180_1430/A01_1/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.3.xfer.xml
  t/data/pacbio/superfoo/60180_1430/A01_1/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.mcd.h5
  t/data/pacbio/superfoo/60180_1430/A01_1/m180302_192953_00127_c101227792550000001823293112071730_s1_X0.metadata.xml
  t/lib/WTSI/NPG/HTS/PacBio/RunPublisherTest.pm
Labels: enhancement, for next release

#165 Updated build scripts
  scripts/minion/install_baton.sh
  scripts/minion/install_hdf5.sh
  scripts/minion/install_irods.sh
  scripts/minion/install_jansson.sh
  scripts/minion/install_jq.sh
  scripts/minion/install_npg_irods.sh
  scripts/minion/install_tears.sh
  scripts/minion/make_minion_dist.sh
Labels: enhancement, for next release

#172 Single server option
  BuildONT.PL
  bin/npg_gridion_run_monitor.pl
  bin/npg_publish_gridion_run.pl
  lib/WTSI/NPG/HTS/ONT/GridIONRunMonitor.pm
  lib/WTSI/NPG/HTS/ONT/GridIONRunPublisher.pm
  t/lib/WTSI/NPG/HTS/ONT/GridIONRunPublisherTest.pm
Labels: bump minor, enhancement, for next release

#178 Updated the samtools and htslib versions to 1.7
  .travis.yml
Labels: enhancement

#183 Publish fastq files during the catchup phase.
  lib/WTSI/NPG/HTS/ONT/GridIONRunPublisher.pm
Labels: bump minor, enhancement, for next release
